server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path=/api/ms1/**
        - id: microservice2
          uri: lb://microservice2
          predicates:
            - Path=/api/ms2/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 